static_resources:
  listeners:
  - address:
      socket_address:
        address: 0.0.0.0
        port_value: 4444
    listener_filters:
    - name: envoy.filters.listener.tls_inspector
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector

    filter_chains:
    - filter_chain_match:
        server_names:
        - kafka1.server.test
      filters:
        - name: ebpf_tcp_proxy_skb
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.EbpfTcpProxySKB
            tcp_proxy:
                cluster: kafka1_cluster
                stat_prefix: kafka1_cluster_stats

    - filter_chain_match:
        server_names:
        - kafka2.server.test
      filters:
        - name: ebpf_tcp_proxy_skb
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.EbpfTcpProxySKB
            tcp_proxy:
                cluster: kafka2_cluster
                stat_prefix: kafka2_cluster_stats

    - filter_chain_match:
        server_names:
        - kafka3.server.test
      filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          cluster: kafka3_cluster
          stat_prefix: kafka3_cluster_stats

  clusters:
  - name: kafka1_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: kafka1_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.1.3
                port_value: 9092

  - name: kafka2_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: kafka2_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.1.3
                port_value: 9093

  - name: kafka3_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: kafka3_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.10.1.3
                port_value: 9094

admin:
  access_log_path: "/var/log/envoy/admin.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8000
